version: '3.1'

services:
  db:
    container_name: db
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - /$PWD/db/:/var/lib/postgresql/data:rw
    ports:
      - 5432:5432
  
  nginx:
    container_name: nginx
    image: nginx:alpine
    restart: always
    volumes:
      - /$PWD/nginx/content:/usr/share/nginx/html:ro
      - /$PWD/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    links:
      - db
      - adminer
  
  adminer:
    container_name: adminer
    image: adminer
    restart: always
    #ports:
    #  - 8080:81

# app:
  #   image: app:latest
  #   restart: always
  #   volumes:
  #     - ./app:/app/
  #   ports:
  #     - "5000:5000"


